# Based on: https://github.com/ClementTsang/bottom/blob/master/.github/workflows/deployment.yml

name: Release

on:
  push:
    tags:
      - v*

env:
  CARGO_TERM_COLOR: always

jobs:
  publish-crate:
    name: Publish Crate
    runs-on: ubuntu-20.04
    needs: publish-to-github
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: ${{ runner.os }}-stable
      - name: Setup
        run: |
          rustup install stable
      - name: Get Version
        run: echo GIT_VERSION="$(git describe --tags | sed 's/^v\(.*\)$/\1/')" >> $GITHUB_ENV
      - name: Prepare Git
        run: |
          git config user.email "github@github.com"
          git config user.name "Github Actions"
          git checkout -b main
          # Use throw-away branch so we don't push the changes to origin
          git checkout -b deploy_branch
      - name: Prepare Crates
        run: |
          # Update cargo version, 
          printf ",s/version = \"0.0.0\"/version = \"$GIT_VERSION\"/g\nw\n" | ed ./humane/Cargo.toml
          git add ./humane/Cargo.toml
          # Commit changes so cargo doesn't complain about dirty repo
          git commit -m "Deploy changes."

      - name: Build
        run: cargo build --release --verbose
      - name: Publish
        working-directory: ./humane
        run: cargo publish --allow-dirty
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}

  publish-npm-package:
    name: Publish NPM package
    runs-on: ubuntu-20.04
    needs: publish-to-github
    defaults:
      run:
        working-directory: ./wrappers/node
    steps:
      - name: Clone
        uses: actions/checkout@v2
      - name: Prepare package
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          npm version $(echo $RELEASE_VERSION | cut -c1-)
          mkdir checksums
          for TARGET in x86_64-unknown-linux-musl x86_64-apple-darwin
          do
            ASSET_NAME="humane-$RELEASE_VERSION-$TARGET.tar.gz.sha256"
            curl -L https://github.com/CloudCannon/humane/releases/download/$RELEASE_VERSION/$ASSET_NAME -o checksums/$ASSET_NAME
          done
      - name: Publish
        run: npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish-to-github:
    name: Publish to Github and Crates
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - build: linux
            os: ubuntu-latest
            rust: stable
            target: x86_64-unknown-linux-musl
            cross: false
            musl: true
          - build: macos
            os: macos-latest
            rust: stable
            target: x86_64-apple-darwin
            cross: false
            musl: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
            target
          key: ${{ runner.os }}-${{ matrix.rust }}

      - name: Install Linker
        if: matrix.cross
        run: |
          sudo apt update
          sudo apt install ${{ matrix.linker }}
      - name: Install Musl Tools
        if: matrix.musl
        run: |
          sudo apt update
          sudo apt install -y musl-tools musl-dev
      - name: Install Rust
        run: |
          rustup install ${{ matrix.rust }}
          rustup target add ${{ matrix.target }}
          rustup show
      - name: Install Chrome
        uses: browser-actions/setup-chrome@latest

      # From https://github.com/Emoun/duplicate/blob/master/.github/workflows/rust.yml
      - name: Get Version
        run: echo GIT_VERSION="$(git describe --tags | sed 's/^v\(.*\)$/\1/')" >> $GITHUB_ENV
      - name: Prepare Git
        run: |
          git config user.email "github@github.com"
          git config user.name "Github Actions"
          git checkout -b main
          # Use throw-away branch so we don't push the changes to origin
          git checkout -b deploy_branch
      - name: Prepare Crates
        run: |
          # Update cargo version, 
          printf ",s/version = \"0.0.0\"/version = \"$GIT_VERSION\"/g\nw\n" | ed ./humane/Cargo.toml
          git add ./humane/Cargo.toml
          # Commit changes so cargo doesn't complain about dirty repo
          git commit -m "Deploy changes."

      - name: Package Crate
        working-directory: ./humane
        run: |
          # Package crate to ensure it works without issue
          cargo package --allow-dirty

      - name: Test Lib
        working-directory: ./humane
        run: cargo run # Humane tests itself when run

      - name: Build
        working-directory: ./humane
        run: RELEASE_VERSION=${GITHUB_REF#refs/tags/} cargo build --release --target ${{ matrix.target }}

      - name: Package Artifacts
        run: |
          src=$(pwd)
          stage=
          case $RUNNER_OS in
              Windows)
                  stage=$(mktemp -d)
                  ;;
              Linux)
                  stage=$(mktemp -d)
                  ;;
              macOS)
                  stage=$(mktemp -d -t tmp)
                  ;;
          esac
          cp target/${{ matrix.target }}/release/humane $stage/
          cd $stage
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          ASSET_NAME="humane-$RELEASE_VERSION-${{ matrix.target }}.tar.gz"
          ASSET_PATH="$src/$ASSET_NAME"
          CHECKSUM_PATH="$ASSET_PATH.sha256"
          tar czf $ASSET_PATH *
          cd $src
          case $RUNNER_OS in
              Windows)
                  sha256sum $ASSET_NAME > $CHECKSUM_PATH
                  ;;
              Linux)
                  sha256sum $ASSET_NAME > $CHECKSUM_PATH
                  ;;
              macOS)
                  shasum -a 256 $ASSET_NAME > $CHECKSUM_PATH
                  ;;
          esac
          if [ "$RUNNER_OS" == "Windows" ]; then
              ASSET_PATH=$(echo "$ASSET_PATH" | sed -e 's/^\///' -e 's/\//\\/g' -e 's/^./\0:/')
              CHECKSUM_PATH=$(echo "$CHECKSUM_PATH" | sed -e 's/^\///' -e 's/\//\\/g' -e 's/^./\0:/')
          fi
          echo "ASSET_PATH=$ASSET_PATH" >> $GITHUB_ENV
          echo "CHECKSUM_PATH=$CHECKSUM_PATH" >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.ASSET_PATH }}
            ${{ env.CHECKSUM_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
